name: Run Tests

on:
  workflow_call:
    inputs:
      browser:
        required: true
        type: string
      shard_index:
        required: true
        type: number
      shard_total:
        required: true
        type: number
      artifact_name:
        required: true
        type: string
      retention_days:
        required: true
        type: number

jobs:
  test-run:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.54.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test --project=${{ inputs.browser }} --shard=${{ inputs.shard_index }}/${{ inputs.shard_total }}
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.artifact_name }}
          path: |
            test-results/
            allure-results/
            playwright-report/
          retention-days: ${{ inputs.retention_days }}
