name: CI Pipeline

on:
  push:
    branches: [main, develop]

jobs:
  full-test:
    uses: ./.github/workflows/full-test-workflow.yml
    with:
      browsers: '["chromium", "webkit"]'
      shards: 4
      retention_days: 30
