name: CI Pipeline

on:
  push:
    branches: [main, develop]

env:
  NODE_VERSION: '18'
  PLAYWRIGHT_BROWSERS_PATH: '0'

jobs:
  lint-format:
    uses: ./.github/workflows/lint-format.yml

  test:
    needs: lint-format
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, webkit]
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    uses: ./.github/workflows/test-run.yml
    with:
      browser: ${{ matrix.browser }}
      shard_index: ${{ matrix.shardIndex }}
      shard_total: ${{ matrix.shardTotal }}
      artifact_name: test-results-${{ matrix.browser }}-${{ matrix.shardIndex }}
      retention_days: 30

  generate-report:
    needs: test
    if: ${{ always() && needs.test.result != 'skipped' }}
    uses: ./.github/workflows/generate-report.yml
    with:
      download_path: all-test-results
      merged_dir: merged-results
      allure_artifact_name: allure-report
      html_artifact_name: html-report
      retention_days: 30
