name: Dependency Update

on:
  schedule:
    - cron: '0 3 * * 1' # Run every Monday at 3 AM UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.54.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Check for outdated packages
        run: npm outdated || true

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format:check

  update-dependencies:
    needs: dependency-check
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.54.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Update dependencies
        run: |
          npm update
          npm audit fix

      - name: Run tests to ensure nothing is broken
        run: npm test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: '🤖 Automated dependency update'
          body: |
            This PR updates dependencies to their latest compatible versions.

            ## Changes
            - Updated npm packages to latest versions
            - Applied security fixes

            ## Checklist
            - [x] Tests pass
            - [x] Code quality checks pass
            - [x] No breaking changes detected

            Please review the changes and merge if everything looks good.
          branch: dependency-update
          delete-branch: true
