name: Full Test Workflow

on:
  workflow_call:
    inputs:
      browsers:
        required: true
        type: string
      shards:
        required: true
        type: number
      retention_days:
        required: true
        type: number

jobs:
  lint-format:
    uses: ./.github/workflows/lint-format.yml

  test:
    needs: lint-format
    strategy:
      fail-fast: false
      matrix:
        browser: ${{ fromJson(inputs.browsers) }}
    uses: ./.github/workflows/test-run.yml
    with:
      browser: ${{ matrix.browser }}
      shards: ${{ inputs.shards }}
      retention_days: ${{ inputs.retention_days }}

  generate-report:
    needs: test
    if: ${{ always() && needs.test.result != 'skipped' }}
    uses: ./.github/workflows/generate-report.yml
    with:
      retention_days: ${{ inputs.retention_days }}