name: Generate Report

on:
  workflow_call:
    inputs:
      retention_days:
        required: true
        type: number

jobs:
  generate-report:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.1
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: |
          apt-get update
          apt-get install -y openjdk-17-jre-headless unzip
          curl -o allure.zip -Ls https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.zip
          unzip allure.zip -d /opt/allure
          rm allure.zip
          echo "/opt/allure/bin" >> $GITHUB_PATH

      - name: Download all test artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare result directories
        run: mkdir -p allure-results playwright-report

      - name: Merge Allure results
        run: find artifacts -type d -name "allure-results" -exec cp -r {}/. allure-results/ \; || echo "No allure-results found"

      - name: Merge Playwright reports
        run: find artifacts -type d -name "playwright-report" -exec cp -r {}/. playwright-report/ \; || echo "No playwright-report found"

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: ${{ inputs.retention_days }}

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: playwright-report
          retention-days: ${{ inputs.retention_days }}
