name: Nightly Tests

on:
  schedule:
    - cron: '0 2 * * *' # Run at 2 AM UTC daily
  workflow_dispatch: # Allow manual trigger

jobs:
  lint-format:
    uses: ./.github/workflows/lint-format.yml

  nightly-test:
    needs: lint-format
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, webkit]
        shardIndex: [1, 2, 3, 4, 5, 6]
        shardTotal: [6]
    uses: ./.github/workflows/test-run.yml
    with:
      browser: ${{ matrix.browser }}
      shard_index: ${{ matrix.shardIndex }}
      shard_total: ${{ matrix.shardTotal }}
      artifact_name: nightly-test-results-${{ matrix.browser }}-${{ matrix.shardIndex }}
      retention_days: 90

  nightly-report:
    needs: nightly-test
    if: ${{ always() && needs.nightly-test.result != 'skipped' }}
    uses: ./.github/workflows/generate-report.yml
    with:
      download_path: nightly-test-results
      merged_dir: merged-results
      allure_artifact_name: nightly-allure-report
      html_artifact_name: nightly-html-report
      retention_days: 90

  notify-failure:
    runs-on: ubuntu-latest
    needs: [nightly-test, nightly-report]
    if: failure()
    steps:
      - name: Notify failure
        run: |
          echo "❌ Nightly tests failed!"
          echo "Check the workflow run for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
