name: Nightly Tests

on:
  schedule:
    - cron: '0 2 * * *' # Run at 2 AM UTC daily
  workflow_dispatch: # Allow manual trigger

jobs:
  full-test:
    uses: ./.github/workflows/reusable/full-test-workflow.yml
    with:
      browsers: '["chromium", "webkit"]'
      shards: 6
      retention_days: 90

  notify-failure:
    runs-on: ubuntu-latest
    needs: full-test
    if: failure()
    steps:
      - name: Notify failure
        run: |
          echo "❌ Nightly tests failed!"
          echo "Check the workflow run for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
