name: PR Check

on:
  pull_request:
    branches: [main, develop]

jobs:
  full-test:
    uses: ./.github/workflows/reusable/full-test-workflow.yml
    with:
      browsers: '["chromium"]'
      shards: 2
      retention_days: 7
