name: Run Tests

on:
  workflow_call:
    inputs:
      browser:
        required: true
        type: string
      shards:
        required: true
        type: number
      retention_days:
        required: true
        type: number

jobs:
  test-run:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.54.1
    strategy:
      matrix:
        shard: ${{ range(1, inputs.shards + 1) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test --project=${{ inputs.browser }} --shard=${{ matrix.shard }}/${{ inputs.shards }}
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ inputs.browser }}-${{ matrix.shard }}
          path: |
            test-results/
            allure-results/
            playwright-report/
          retention-days: ${{ inputs.retention_days }}